#! /usr/bin/python
# -*- coding: utf-8 -*-

#IMPORTANT!: TRANSLATION TO OTHER LANGUAGE
#1) MAKE A COPY OF THIS FILE AND RENAME IT "M_YOURLANGUAGE.PY"
#2)TRANSLATE INTO YOUR LANGUAGE THE SENTENCE ON THE RIGHT SIDE OF COLON (:) - USE ASCII 128 ONLY.
#3)DO NOT MODIFY OR CANCEL THE %s VARIABLES!! DO NOT MODIFY ANYTHING OUTSIDE OF SENTENCES " " !!
#4)IN "M_CONF.PY" CHANGE THE VALUE OF RC_lang = "ITA" TO RC_lang = "YOURLANGUAGE"
#5)RESTART REDCAP

RC_outputs = {
"accident":"^5%s ^3non ha fatto attenzione e si e' ammazzato da solo",
"adminrights": "^3Assegnato livello admin a ^5%s",
"alias": "^3Alias di ^5%s:^3",
"antirecon": "^5%s ^1kikkato per doppia connessione in meno di ^6%s",
"balanceauto":"^3Non necessario: il bilanciamento avviene in ^7AUTOMATICO ^3all'inizio di ogni round",
"balanceclan":"^3Non possibile quando il bilanciamento e' in modalita'  ^7CLAN",
"balancexecuted": "^3Bilanciamento effettuato.",
"balancemanual": "^3Il bilanciamento verra' effettuato ^7se necessario ^3a inizio round",
"balancemode": "^3Bilanciamento teams ^6%s",
"balancenoneed": "^3Teams equivalenti. Chiedere eventualmente lo shuffle ad un admin",
"balanceoff":"^3La funzione bilanciamento non e' attiva. Usare il comando ^6!ab ^3 per attivarla",
"ban": "^1La presenza di ^5%s ^1non e' piu' gradita su questo server",
"bestplayers": "^3Migliori player:",
"caricoplayer": "^3Caricati i dati di ^5%s da DB",
"dbnick":"^3Assegnato ^5%s ^3come nick principale",
"mapskill": " ^5%s^3 skill di mappa: ^6%s",
"executed": "^3Comando ^6%s ^3eseguito",
"forgiven": "^3Player ^5%s ^3perdonato",
"forgivenall": "^3Tutti i compagni sono stati perdonati",
"forgivenone": "^3Non hai niente da perdonare a ^5%s",
"flood": "^5%s ^1kikkato per flooding",
"guidchange": "^1CHEATER FOUND: ^5%s ^1cambio GUID in game. ^1Kicked",
"headshot": "^5%s ^7%s HS ^3(^6%s o/o^3)",
"insults": "^3Gli insulti non sono permessi. ^1Ancora %s volte e verrai kikkato",
"invalidguid": "^1PROBABILE CHEAT: ^5%s ^1kikkato per GUID non regolare",
"invalidnick": "^5%s ^1kikkato per NICK non regolare",
"levassigned":"^3Assegnato livello ^6%s ^3a ^5%s.",
"lownotoriety": "^5%s ^1Affidabilita bassa o QKEY nuova: ^6%s ^3contro ^6%s ^3richiesta",
"lownotoriety2": "^3Ritorna tra ^6%s ^3giorni con la stessa QKEY",
"moreinfo": "Scrivi ^5!help cmd ^3per info sul comando",
"movedtoblue": "^3Non %s spostato nei blu: ^5%s",
"movedtored": "^3%s spostato nei red: ^5%s",
"muteall": "^1Muto/Smuto tutti!",
"muted":"^5%s ^3mutato in quanto era mutato all'ultima disconnessione",
"newfake":"^3Rilevato nuovo fake. Persi ^6%s ^3punti di affidabilita. La tua affidabilita e adesso ^6%s ",
"nickchanges": "^5%s ^1kikkato per troppi cambi nick (%s)",
"noavailcmd": "^3Comando non disponibile in fase di avvio.",
"noclearcfg": "^3Configurazione ambigua o inesistente.",
"nocleartarget": "^3Nick ambiguo. Riprova o usa lo slot ID",
"noclearmap": "^3Mappa ambigua o inesistente. Riprova o usa ^6!cmd nomemappa",
"noIDfound": "^3Player ID non trovato. Usa il comando ^2!find ^3per trovare l'ID giusto",
"nolevel": "^3Comando di ^7livello %s. ^3Il tuo livello e' ^7%s",
"norecorderase": "^1Non puoi cancellare un record",
"notimefromini": "^1Non puoi chiamare un voto nei primi 60 secondi della mappa",
"notimetocmd": "^3Devi aspettare ancora ^7%s minuti ^3per chiamare questo comando",
"not_update": "^3Notoriety di ^5%s ^3= ^7%s",
"not_changed": "^3MIN. Notoriety per giocare sul server: ^6%s",
"nuked": "^3Nuke lanciata su ^5%s ^3da ^5%s",
"ora": "^3Sono le ^7%s",
"punishtodeath": "^5%s ^3la corte marziale ti ha condannato a morte per l'omicidio di ^5%s",
"pwdset": "^3Password inserita. Sara' attiva dal prossimo map load",
"record_alltime": "^2RECORD ASSOLUTO di ^5%s ^6%s kills",
"record_daily": "^2RECORD ODIERNO di ^5%s ^6%s kills",
"record_monthly": "^2RECORD MENSILE di ^5%s ^6%s kills",
"record_no_not": "^5%s, ^3Affidabilita troppo bassa per validare un record",
"record_no_ppl": "^3meno di ^7%s ^3persone in game. Record di  ^5%s ^3non convalidato",
"record_personal": "^2Record personale di ^5%s ^6%s kills",
"record_weekly": "^2RECORD SETTIMANALE di ^5%s ^6%s kills",
"resetdone": "^3Record %s cancellato.",
"resetnotdone":"^1Errore. ^3Specificare un parametro: %s",
"restart": "^1 Riavvio RedCap...",
"salvoplayer": "^3Salvo i dati di ^5%s",
"silentmode": "^3Modalita' silenziosa ^6%s",
"skill": "^3Skill: ^7%s ^3Instantanea: ^7%s ^3Streak: ^7%s ",
"smited": "^3La forza del destino ha colpito ^5%s",
"space":"^3Slots pieni. ^5%s ^3entra in gioco o sarai kikkato.",
"spacekicked": "^3Server pieno. Spettatore ^5%s ^3kikkato.",
"spamadded":"^3Frase aggiunta",
"spamerased":"^3Frase cancellata",
"spamnotfound":"^1Frase non trovata",
"startup":"^2RedCap in fase di avvio",
"startupend": "^3Fase di avvio terminata. ^2RedCap operativo",
"stillban": "^5%s, ^1sei ancora bannato fino al ^6%s",
"suicide": "^1Suicidio: ^3penalizzazione di ^6%s ^3punti skill",
"tbkicked":"^3kikkato ^5%s",
"tempban": "^5%s ^1bannato per ore ^7%s",
"tempbanmax": "^3Il massimo ban temporaneo e' di ore ^6%s",
"thit": "^1NO TEAMHITS! ^3Applicata penalita skill. Livello warning ^1%s ",
"tkill": "^1NO TEAMKILL! ^3Applicata penalita skill. Livello warning ^1%s ",
"toohighlevel":"^1Non puoi assegnare livelli superiori al tuo che e' ^6%s",
"toomanyres":"^3Troppi risultati ^5(%s). ^3Specificare meglio.",
"top": "^2%s record: ^4%s ^5%s ^2il %s #",
"unbandone": "^3Unban eseguito. In caso di problemi sbannare l'IP utilizzando il comando ^2!cmd removeIP x.y.z.k",
"voteON":"^3Il voto e' ora attivo per ^7%s ^3secondi",
"voteOFF":"^3voto disabilitato",
"warbaseloaded" : "^2Modalita war. ^3Carico config standard ...",
"warloaded": "^2Modalita' war. ^3Carico %s ...",
"warning":"^5%s ^1kikkato per somma di warning",
"warunloaded": "^2Fine WAR. ^3Ricarico %s ...",
"wrongcmd":"^1Questo non e un comando ^2RedCap!",
"youcanuse": "^3Puoi usare: ",
}

RC_help = {
    "al":" ^6target ^3Shows target's alias.",
    "ab":" ^3Switches team autobalance ON/MANUAL/OFF/CLAN.",
    "ban":" ^6target ^3Permanently bans target (also ^6!unban^3exists).",
    "tm":" ^3or ^6!teams ^3Ask RedCap for a teambalance at round end.",
    "v":" ^3Enables vote for some time",
    "cy":" ^3Cycles immediately to the next map.",
    "find":" ^6target ^3find target ID in DB.",
    "dbnick":" ^6target ^3Set target's nick as his main nick in DB.",
    "cmd":" ^6command ^3same as /rcon command.",
    "f":" ^6target [r,b,s] ^3Moves target to Red, Blue or Spect.",
    "fp":" ^6[target] ^3forgive target for thit or tkill. if no target if forgive all your teammates",
    "fall":" ^6target ^3fully forgive a player for tk or th.",
    "gears":"^3Armi ammesse ^60 (all)^3,^6 snip^3,^6 spas^3,^6 auto^3or^6 UrT string",
    "help": "^6[command] ^3Shows help (on command if specified).",
    "info":" ^3Shows some info about game server and RedCap itself.",
    "kk":" ^6target ^3Kicks target.",
    "lev":" ^6target ^3Assign a level to target.",
    "map":" ^6map ^3Loads specified map.",
    "maplist":" ^3Shows a list of all the maps availables on the gameserver.",
    "m":" ^6target ^3mute target.",
    "mall":" ^3mute all the players in game.",
    "notoriety":" ^3Change min. trust level required to play on gameserver.",
    "n":" ^6target ^3nukes target.",
    "ora":" 3Shows server time.",
    "pwd":" ^6pwd ^3Sets a password on the game server.",
    "restart":" ^3Restart the RedCap.",
    "rere":" ^6rec ^3Resets a record (Day, Week, Month, All).",
    "silent":" ^3Switch between silent and verbose mode.",
    "sk":" ^6target ^3Shows target's skill.",
    "s":"^6[n] target ^3Slaps target n times (1 if no 'n' specified).",
    "sm":" ^6target ^3Istantly kills target.",
    "spam":" ^6msg ^3adds a message from spam list (!unspam erase it).",
    "spamlist":" ^3Lists all spam messages.",
    "status":" ^6[target] ^3Gives several details about player(s).",
    "tban":" ^6[hours] ^3Temporary ban. If no hours specified it is 1",
    "top":" ^3Shows top records.",
    "trust":"^6[value] ^3Increases or decreases (!untrust) player's reliability level.",
    "unwar":" ^3Unload war mode setting the game server to its standard configuration.",
    "war":" ^6[cfg] ^3Loads a CW config and set the gameserver in war mode.",
}

RC_kills = {        #messaggi di killstreak
0 :"^5%s ^3ha fermato la serie di ^5%s",
1 :"",
2 :"",
3 :"",
4 : '^5%s^3 e\' in forma...',
5 : '^5%s^3 si sta scaldando: ^15 ^3kills!',
6 : '^3 ci sono sei nuove vedove grazie a ^5%s ',
7 : '^4%s^3 7 kill? Non male!',
8 : '^3Ottava kill per ^5%s, ^3stara\' camperando?',
9 : '^5%s^3 9 kills. Record in vista?',
10 : '^5%s^3 1^40 ^3K^4I^5L^6L^8S^9!! ',
11 : '^5%s^3 11 kills! Non sei un noob...',
12 : '^5%s^3 12 kills...aimbot or wallhack?',
13 : '^5%s^3 13 kills? ^1Attenzione c\'e\' un PRO in game!',
14 : '^3 14 kills? Fermate il soldato ^5%s!',
15 : '^5%s^3 15 kills? are you Kabal?!',
16 : '^5%s^3 16 kills? 16 kills? one more and i\'ll kick you!!',
17 : '^54%s^3 17 kills? I was kidding!',
18 : '^5%s^3 18 ^1You are more pro than before!',
19 : '^5%s^3 19 kills! Are you playing against fools!?!?',
20 : '^5%s^3 20 ^3KILLS^4!^5!^6!',
21 : '^5%s^3 21 kills...i can\'t believe it! :-(',
22 : '^5%s^3 22 kills? 1337!',
23 : '^5%s^3 23 kill? ^4ok guys, John Rambo is here',
24 : '^5%s^3 24 corpses... ^4bigger massacre than waco!',
25 : '^5%s^3Kill counter is OVER! ^3U^4N^6B^1E^7L^8I^9E^0V^1A^3B^5L^3E^6!',
}

RC_logoutputs = {
"command": "%s alias %s (lev:%s) ha usato: %s (lev:%s)",
}

RC_status = {
1: "^3Player ^5%s ",
2: "^3Skill:^7%s ",
4: "^3Istskill:^7%s ",
8: "^3Streak:^7%s ",
16: "^3Rounds:^7%s ",
32: "^3Affidabilita:^7%s ",
64: "^3Slot:^7%s ",
128: "^3Registrato:^7%s ",
256: "^3IP:^7%s ",
512: "^3Level:^2%s ",
1024: "^3Warning:^7%s ",
2048:" ^3Ultima visita: ^7%s ",
4096: "^3Alias:^7%s ",
8192: "^3da ^7%s",
}
